FROM ubuntu:14.04
MAINTAINER Xiaolei Huang <xiaoleihuangccnu@gmail.com>

USER root

RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
    &&apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install -y software-properties-common \
    && add-apt-repository -y ppa:webupd8team/java \
    && apt-get update -y \
    && apt-get install -y oracle-java8-installer \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /var/cache/oracle-jdk8-installer \
    && apt-get install -y git libpcap-dev maven
    
# Encoding setting
RUN localedef -c -f UTF-8 -i en_US en_US.UTF-8 \
    && export LC_ALL=en_US.UTF-8

#　Setting working directory inside of container
WORKDIR /OpenADS

# Define commonly used JAVA_HOME variable
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle


